# Les 2: The Python Imaging Library

<div class="alert alert-info" role="alert">

<b> Doel van dit college </b>
    
In dit notebook bekijken we hoe je afbeeldingen kan maken en bewerken in Python. We gaan ook een manier introduceren die het ons gemakkelijk maakt een stuk van het Euclidische vlak af te beelden naar afbeeldingen van verschillende
groottes. Tenslotte zien jullie hoe je je code kan verpakken in een bestand dat je kan gebruiken in andere werkbladen. 
</div>

<img src=cats.png width=80%>


Het beste package voor afbeeldingen is de Python Imaging Library (PIL).
Als je een afbeelding wilt inladen en bekijken moet je uit dit package de class <code>Image</code> importeren:

<ul>
    <li> Om een afbeelding in te laden gebruik je het commando
        <code>im = Image.open('filename.png')</code>.
        Dit leest de afbeelding filename.png in in de variabele <code>im</code>. 
    <li> Om de afbeelding <code>im</code> te laten zien gebruik je het commando 
        <code>im.show()</code>. In Jupyter Notebooks kun je ook code-blokken met de regel <code>im</code> eindigen om de afbeelding (maximaal één) direct in de notebook te weergeven. 
    <li> Je kan ook de afmetingen van een afbeelding bekijken via 
        <code>im.size</code>:
        dit is een tuple dat de breedte en hoogte van de afbeelding bevat.
    <li> Je kan ook een lege afbeelding maken:
        <code>im = Image.new('RGBA', (400, 200), color = 'white' )</code>
        geeft een lege afbeelding die 400 pixels breed is en 200 hoog en alle pixels zijn wit gekleurd.
    <li>Om een afbeelding op te slaan gebruik je het commando
        <code>im.save('filename.png')</code>.
</ul>

<div class="alert alert-success">
<b>Opdracht 1</b>
    
Importeer de packages <code>Image</code> en <code>ImageDraw</code> uit <code>PIL</code>. Laad de afbeelding  cat.png in en maak een nieuwe afbeelding  <code>im2</code> met dezelfde afmetingen die helemaal blauw is gekleurd. 
</div>

In [ ]:
from PIL import Image, ImageDraw

In [ ]:
im = Image.open('cat.png')


In [ ]:
im.getpixel((0, 0))

In [ ]:
im2 = Image.new('RGBA', (309, 307), color = 'blue' )
im2

## Spelen met kleuren en plaatjes

Een afbeelding kan je beschouwen als een array met afmetingen <code>im.size</code>. Elke pixel wordt gerepresenteerd met een 4-tuple die de hoeveelheid rood, groen, blauw en de alpha (ondoorzichtigheid of opaciteit) van die pixel weergeeft op een schaal van 0 tot 255. Je kan deze waarde aflezen met <code>getpixel</code> en aanpassen met <code>putpixel</code>.

<ul>
    <li> <code>print(im2.getpixel((0, 0)))</code> geeft $(0, 0, 255, 255)$ omdat de pixel in de linkerbovenhoek blauw is en ondoorschijnend.
    <li> <code>im2.putpixel((9, 9), (255, 0, 0, 128))</code> plaatst een halfdoorschijnende rode pixel in de linkerbovenhoek.
</ul>

<b>Let op!</b> Het is belangrijk om in de gaten te houden dat als je het pakket PIL gebruikt, de coördinaten anders werken dan in het gewone vlak. Meer bepaald als <code>im.size</code> $= (w,h)$, dan heeft
de pixel in de linkerbovenhoek coördinaten $(0, 0)$, die in de rechterbovenhoek $(w-1, 0)$, die in de rechteronderhoek $(w-1, h-1)$ en die in de linkeronderhoek $(0, h-1)$.     


<b>Merk op:</b>
Het is ook mogelijk om te werken met RGB-afbeeldingen i.p.v. RGBA-afbeeldingen. In dat geval gebruik je <code>im = Image.new('RGB', (400, 200), color = 'white')</code> om een afbeelding te maken en moet je 3-tuples voor de kleuren gebruiken.

<div class="alert alert-success">
<b>Opdracht 2</b>
    
Maak een gele afbeelding met afmetingen $(100,100)$ met een rode diagonaal (kleur alle punten met coordinaten $(x,x)$ rood).
 
Laad de afbeelding cat.png in en vervang de witte achtergrond door een doorschijnende. Met andere woorden: elke pixel van de vorm $(255,255,255,255)$ moet een pixel $(255,255,255,0)$ worden. Kan je er ook voor zorgen dat de ogen wit blijven?
</div>

In [ ]:
im3 = Image.new('RGBA', (100, 100), color = 'yellow' )
for i in range(100):
    im3.putpixel((i, i), (255, 0, 0, 255))
im3

In [ ]:
im4 = Image.open('cat.png')

for i in range(309):
    for j in range(307):
        if im4.getpixel((i, j))[0] == 255 and im4.getpixel((i, j))[1] == 255 and im4.getpixel((i, j))[2] == 255:
            im4.putpixel((i, j), (0, 0, 0, 100))
            
for i in range(40, 65):
    for j in range(95, 120):
        if im4.getpixel((i, j))[0] == 0:
            im4.putpixel((i, j), (255, 255, 255, 255))
            
for i in range(85, 110):
    for j in range(95, 120):
        if im4.getpixel((i, j))[0] == 0:
            im4.putpixel((i, j), (255, 255, 255, 255))
im4

In [ ]:
im4

In [ ]:
# where are the eyes?

im4.putpixel((97, 95), (0, 0, 0, 255))
im4.putpixel((97, 120), (0, 0, 0, 255))
im4.putpixel((110, 108), (0, 0, 0, 255))
im4.putpixel((85, 108), (0, 0, 0, 255))

im4.putpixel((52, 95), (0, 0, 0, 255))
im4.putpixel((52, 120), (0, 0, 0, 255))
im4.putpixel((65, 108), (0, 0, 0, 255))
im4.putpixel((40, 108), (0, 0, 0, 255))

im4

## Plaatjes manipuleren


In combinatie met numpy kan je ook operaties op afbeeldingen doen. Je kan van een afbeelding een ndarray maken met
<code>ar = np.asarray(im)</code>.
Omgekeerd kan je een array omzetten naar een afbeelding met
<code>ar = Image.fromarray(ar)</code>.

<div class="alert alert-success">
<b>Opdracht 3</b>
    
Hieronder staat een voorbeeld uitgewerkt waarbij in het prentje de rood-, groen- en blauwgehaltes uitgemiddeld worden zodat het prentje grijs wordt. Merk op dat we de functie <code>np.uint8</code> gebruiken om ervoor
te zorgen dat de kleurwaarden integers zijn tussen 0 en 255.
    
Pas de code aan zodanig dat in het prentje het rood- en blauwgehalte van de kleuren wordt omgewisseld.
</div>    

In [ ]:
import numpy as np

ar = np.asarray(Image.open('cat.png'))
ar_new = np.array([[[0.33 * u[0] + 0.33 * u[1] * 0.33 * u[2],
                    0.33 * u[0] + 0.33 * u[1] * 0.33 * u[2],
                    0.33 * u[0] + 0.33 * u[1] * 0.33 * u[2],
                    u[3]] for u in row] for row in ar])
im = Image.fromarray(ar_new.astype(np.uint8))
im

In [ ]:
ar2 = np.asarray(Image.open('cat.png'))
ar2_new = np.array([[[u[2], u[1], u[0], u[3]] for u in row] for row in ar2])
im = Image.fromarray(ar2_new.astype(np.uint8))
im

Om op een afbeelding <code>im</code> lijnen te teken kan je de <code>ImageDraw</code> klasse gebruiken. 
Eerst maak je een <code>Draw</code>-object met
    <code>draw = ImageDraw.Draw(im)</code>
en daarna kan je de functie <code>line</code> gebruiken om lijnen te tekenen tussen pixelcoördinaten in een lijst.
Het commando

<code>img1.line([(10, 10), (10, 90), (90, 90), (90, 10), (10, 10)], fill = 'red', width = 1)</code> 

tekent een rood vierkant met dikte 1. 
Interessant om te weten is dat de coördinaten in dit geval geen gehele getallen hoeven te zijn (wat bij <code>getpixel</code> en <code>putpixel</code> wel het geval is). 

Je kan ook ellipsen en gevulde veelhoeken tekenen. 

<div class="alert alert-success">
<b>Opdracht 4</b>

Kijk naar het voorbeeld hieronder om te zien hoe deze commando's werken.
Gebruik deze commando's om een Mondriaan-achtige tekening te maken. 
</div>    

In [ ]:
from PIL import ImageDraw

im = Image.new('RGBA', (100, 100), color=(128, 255, 255, 255))
draw = ImageDraw.Draw(im)
draw.line([(10, 10), (10, 80), (90, 90), (90, 10), (10, 10)],
          fill="yellow",
          width=3)
draw.ellipse([(20, 30), (50, 60)], fill='blue', outline='orange', width=2)
draw.polygon([(65, 30), (80, 40), (75, 60)],
             fill=(128, 255, 128, 255),
             outline='black')
im

## Van het vlak naar een canvas en terug


Zoals eerder gezegd is de standaardinstelling in PIL dat de pixel in de linkerbovenhoek coördinaten $(0, 0)$ heeft. In het vervolg van dit vak zal het blijken dat het heel handig is om andere coördinaten toe te kennen aan
de linkerbovenhoek en de rechteronderhoek van de prent. Op die manier kunnen we het stuk van het vlak dat op de afbeelding staat en de breedte en hoogte van de afbeelding apart wijzigen.


<img src=kader.png width=80%>    

<div class="alert alert-info" role="alert">

<b>Wiskundige opdracht 1 (Een formule voor deze transformatie)</b>

Bepaal de formule achter pixelco. Stel je hebt een punt $(x, y)$ op het vlak en je wilt dit afbeelden op de canvas rechts, welke transformatie doet dit? Tegelijkertijd wil je ook een schaling doen, namelijk dat het punt $(u_0, v_0)$ afgebeeld wordt op $(0, 0)$ en dat het punt $(u_1, v_1)$ afgebeeld wordt op $(w, h)$. Vul je antwoord hieronder (dubbelklik op dit cel om in Markdown te kunnen schrijven) met een korte toelichting van hoe je hebt gewerkt

\begin{align*}
\text{pixelco}: \mathbb{R}^2 \to \mathbb{R}^2 :   
\begin{pmatrix}
x\\
y
\end{pmatrix}
\mapsto
\begin{pmatrix}
??\\
??
\end{pmatrix}
\end{align*}


Om dit te doen gaan we een functie <code>pixelco(punt, frame, size)</code> maken die de coördinaten van een punt in het vlak omzet in de coördinaten van de overeenkomstige pixel in de afbeelding. 

De input voor deze functie bestaat uit drie delen: <code>point</code> stelt de coördinaten van het punt $(x, y)$ voor, 
de variabele <code>size</code> is een tuple $(w,h)$ met de breedte en hoogte van de prent in pixels en <code>frame</code> ziet er uit als <code>((u0, v0), (u1, v1))</code> waarbij $(u_0,v_0)$ de coördinaten van de linkerbovenhoek van de prent voorstelt en $(u_1,v_1)$ die van de rechteronderhoek.

<div class="alert alert-success">
<b>Opdracht 5</b>
    
Implementeer de functie <code>pixelco(point, frame, size)</code> en schrijf ook een
functie <code>pointco(pixel, frame, size)</code> die het omgekeerd doet: gegeven de coördinaten van de pixel berekent het die van het punt.
</div>

<b>Opmerking:</b>
Voor een gegeven frame en size kan je <code>pixelco</code> en <code>pointco</code> beschouwen als twee functies die elkaars inverse zijn.
\begin{align*}
\mathtt{pixelco}:\begin{pmatrix}x\\y\end{pmatrix}
\mapsto
\begin{pmatrix}\frac{w}{u_1-u_0}&0\\0&\frac{h}{v_1-v_0}\end{pmatrix}
\begin{pmatrix}x\\y\end{pmatrix}+
\begin{pmatrix}\frac{-u_0w}{u_1-u_0}\\\frac{-v_0h}{v_1-v_0}\end{pmatrix}
\hspace{2cm} \mathtt{pointco}=\mathtt{pixelco}^{-1}
\end{align*}

<br></br>

Deze functies zijn ook voorbeelden van <i>affiene transformaties</i> die jullie gezien hebben in Les1. In het hoorcollege morgen zullen we meer aandacht besteden aan de eigenschappen van zulke transformaties.

In [1]:
def pixelco(point, frame, size):
    x, y = point[0], point[1]
    u0, v0 = frame[0][0], frame[0][1]
    u1, v1 = frame[1][0], frame[1][1]
    w, h = size[0], size[1]
    return ((x - u0) * w / (u1 - u0), (y - v0) * h / (v1 - v0))


def pointco(point, frame, size):
    a, b = point[0], point[1]
    u0, u1 = frame[0][0], frame[0][1]
    v0, v1 = frame[1][0], frame[1][1]
    w, h = size[0], size[1]

    return ((u1 - u0) / w * a + u0, (v1 - v0) / h * b + v0)


frame = ((-1, 1), (1, -1))
size = (200, 300)
pixelco((-0.75, 0.5), frame, size)
#pointco((25, 75), frame, size)

(25.0, 75.0)

In [ ]:
"""
Uitwerking met gebruik van klasse aff
"""

from numpy import linalg as la
import numpy as np
from FunctiesWeek1 import *


def pixelco_aff(frame, size):
    u0, v0 = frame[0][0], frame[0][1]
    u1, v1 = frame[1][0], frame[1][1]
    w, h = size[0], size[1]
    return aff([[w / (u1 - u0), 0], [0, h / (v1 - v0)]],
               [-u0 * w / (u1 - u0), -v0 * h / (v1 - v0)])


def pointco_aff(frame, size):
    return pixelco_aff(frame, size).inverse()

In [ ]:
lijst = [(43, 75), (40, 30), (80, 18),
         (100, 4), (130, 13), (140, 34), (133, 75), (80, 135), (70, 168),
         (80, 190), (103, 154), (165, 153), (243, 205), (288, 300), (240, 260),
         (145, 260), (144, 483), (100, 483), (133, 468), (133, 258), (66, 240),
         (39, 190), (43, 141), (112, 50), (80, 40)]
lijst2 = [pointco(punt, ((-2, 2), (2, -2)), (200, 200)) for punt in lijst]
lijst2

<div class="alert alert-warning">

<b> Test je functie</b>
    
Voor de volgende invoer
<code>frame = ((-1, 1), (1, -1)), size = (200, 300)</code>
zou je voor <code>pixelco((-0.75, 0.5), frame, size)</code> de output <code>(25.0, 75.0)</code> moeten krijgen. 
    
Omdat de functies elkaars inverse zijn, komt er als het goed is bij <code>pointco((25, 75), frame, size)</code> dus <code>(-0.75, 0.5)</code> als output uit.
</div>

<div class="alert alert-success">

<b>Opdracht 6</b>
    
Maak een functie <code>draw_list(lijst, frame, size)</code> die, gegeven een lijst met punten, een afbeelding met afmetingen <code>size</code> maakt en returnt met daarin een polygon met die punten als hoekpunten. Gebruik je functie <code>pixelco</code> om de coordinaten van de punten om te zetten in pixels in de afbeelding.
    
Als je functie werkt dan geeft <code>draw_list(LIST1, ((-2, 2), (2, -2)), (200, 200))</code> een vierkant met zijdes van 100 pixels in het midden van een prent die 200x200 pixels is. Welke figuur geeft de tweede lijst? Maak een opgevulde versie met de juiste keur. 
</div>


In [ ]:
def draw_list(lijst, frame, size):
    im = Image.new('RGBA', size, color='white')
    draw = ImageDraw.Draw(im)
    lijst2 = [pixelco(punt, frame, size) for punt in lijst]
    draw.line(lijst2, fill="pink", width=3)
    return im


def draw_list_pixels(lijst, frame, size):
    im = Image.new('RGBA', size, color='white')
    draw = ImageDraw.Draw(im)
    draw.polygon(lijst, fill="pink")
    return im

In [ ]:
LIST1 = [(-1, -1), (1, -1), (1, 1), (-1, 1), (-1, -1)]
draw_list(LIST1, ((-2, 2), (2, -2)), (400, 400))

In [ ]:
LIST2 = [(43, 75), (40, 30), (80, 18),
         (100, 4), (130, 13), (140, 34), (133, 75), (80, 135), (70, 168),
         (80, 190), (103, 154), (165, 153), (243, 205), (288, 300), (240, 260),
         (145, 260), (144, 483), (100, 483), (133, 468), (133, 258), (66, 240),
         (39, 190), (43, 141), (112, 50), (80, 40)]

LIST3 = [(-1.1400000000000001, 0.5), (-1.2, 1.4),
         (-0.3999999999999999, 1.6400000000000001), (0.0, 1.92),
         (0.6000000000000001, 1.74), (0.8000000000000003, 1.3199999999999998),
         (0.6600000000000001, 0.5), (-0.3999999999999999, -0.7000000000000002),
         (-0.5999999999999999, -1.3599999999999999),
         (-0.3999999999999999, -1.8000000000000003),
         (0.06000000000000005, -1.08), (1.3000000000000003, -1.06),
         (2.8600000000000003, -2.0999999999999996), (3.76, -4.0), (2.8, -3.2),
         (0.8999999999999999, -3.2), (0.8799999999999999, -7.66), (0.0, -7.66),
         (0.6600000000000001, -7.359999999999999), (0.6600000000000001, -3.16),
         (-0.6799999999999999, -2.8), (-1.22, -1.8000000000000003),
         (-1.1400000000000001, -0.8199999999999998), (0.2400000000000002, 1.0),
         (-0.3999999999999999, 1.2)]

In [ ]:
draw_list_pixels(LIST2, frame, size)

<div class="alert alert-success">

<b>Opdracht 7</b>

Beschouw de affiene transformatie <code>TRANS4 = aff([[.5, -.87], [.87, .5]], [0, 0])</code>. Gebruik de samenstelling van transformaties uit Les1 om deze twee, drie en vier keer toe te passen op de elementen van <code>LIST1 = [(-1, -1), (1, -1), (1, 1), (-1, 1)]</code> (of een andere lijst naar keuze).
    
Maak een tekening van de resultaten met de functie <code>draw_list</code> uit deze les.

In [ ]:
TRANS4 = aff([[.5, -.87], [.87, .5]], [0, 0])
lijst = LIST3
draw_list(lijst, ((-4, 4), (4, -8)), (200, 200))

In [ ]:
lijst = [TRANS4 * point for point in lijst]
draw_list(lijst, ((-4, 4), (4, -8)), (200, 200))


<div style="background-color: #ffcc66 ; padding: 10px;">

<b>Begripsopdracht (goed om gaan met punten en pixels)</b>

In deze Notebook hebben jullie de twee functies <code>pixelco</code> en <code>pointco</code> gemaakt. Kijk nog een keer terug naar opdrachten 5 en 6 en de lijsten die we daar geven. Begrijpen jullie waarom deze twee functies nuttig en nodig zijn? Begrijp je het nog niet? Neem even een pauze en kom over een uurtje terug, ga hierover nadenken en lees Sectie 1.3 nog een keer door. Schrijf hieronder in eigen woorden waarom deze twee functies nodig zijn?

<i>Dubbelklik hier en schrijf je reactie.</i>

## Functies verzamelen in je Spyder-bestand


<div class="alert alert-info" role="alert">
<b>Opdracht</b>
<ul>
<li> Kopieer de code voor de functies <code>draw_list</code>, <code>pixelco</code> en <code>pointco</code> in je Spyder bestand <code>week1.py</code>. Sla dit bestand in hetzelfde directory als deze notebook. </li>
    <li> Post je zelfgemaakte Mondriaan op canvas.</li>
    <li> Post een afbeelding van een lijst die je getransformeerd hebt via verschillende affiene transformaties op Canvas. </li>
</ul>
</div>

